version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
      - LOG_LEVEL=INFO
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_DB_DIR=/app/chromadb_data
    volumes:
      - ./backend/conversations.json:/app/conversations.json
      - ./backend/chromadb_data:/app/chromadb_data
      - backend_logs:/app/logs
    networks:
      - evolveui-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
      - REACT_APP_VERSION=1.1.0
    networks:
      - evolveui-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

volumes:
  backend_logs:
    driver: local

networks:
  evolveui-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16