# DEPRECATED: This docker-compose.yml file has been moved to the project root
# Please use the docker-compose.yml file in the project root directory instead
# 
# To start EvolveUI with Docker:
# 1. cd .. (go to project root)
# 2. ./docker-start.sh (recommended)
#    OR
# 3. docker compose up --build
#
# This file is kept for reference but may be removed in future versions

version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=host.docker.internal:11434
    volumes:
      - ./backend/conversations.json:/app/conversations.json
    networks:
      - evolveui-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    networks:
      - evolveui-network

networks:
  evolveui-network:
    driver: bridge